### ISSUE TITLE
no option to input port # in bf_session 

### ISSUE THREAD

**Issue by ghost** [batfish/ansible#104]
We have batfish deployed in K8 cluster with non-default ports, and require ansible playbooks to connect from other various hosts to batfish (not localhost)

bf_session script only takes host and name as input, would be useful if we can provide port # as well

**Comment by sfraint** [comment]
Hey @gowthamt90 , you should be able to supply additional [`Session` parameters](https://github.com/batfish/pybatfish/blob/master/pybatfish/client/session.py#L307) like `port_v1` and `port_v2` under the `parameters` field, e.g.
```
- bf_session:
    host: 10.10.10.10
    name: my_session
    parameters:
      ssl: true
      port_v1: 9997
      port_v2: 9996
```
